// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_production.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzIPHyuNz9B_LxmenCWY2p69TMIZmOUzc',
    appId: '1:907236156568:android:31b28a354fc92bd7555ced',
    messagingSenderId: '907236156568',
    projectId: 'marketlens360-d8e72',
    storageBucket: 'marketlens360-d8e72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvlszyyVKUPlx6gM9VfTrpNZTVv91Te24',
    appId: '1:907236156568:ios:ee6d1a5acd3e990c555ced',
    messagingSenderId: '907236156568',
    projectId: 'marketlens360-d8e72',
    storageBucket: 'marketlens360-d8e72.firebasestorage.app',
    androidClientId: '907236156568-rjl033hfmu1gp9q9glujof63tqal5ect.apps.googleusercontent.com',
    iosClientId: '907236156568-p1g9i742bb3g7pkli5mfu4ebbb6cbmt0.apps.googleusercontent.com',
    iosBundleId: 'com.marketlens.marketlens360mobile',
  );
}
