// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_development.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYKmw81g6FYFMtYsvK0_rstgYa-SBXR5c',
    appId: '1:1006258054322:android:816e50d6ac81532a7315ab',
    messagingSenderId: '1006258054322',
    projectId: 'marketlens360dev',
    storageBucket: 'marketlens360dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8REbfsMbv1D3NWB8UEmZE-TOqIrksn3U',
    appId: '1:1006258054322:ios:3d539306e1ff2d6a7315ab',
    messagingSenderId: '1006258054322',
    projectId: 'marketlens360dev',
    storageBucket: 'marketlens360dev.firebasestorage.app',
    androidClientId: '1006258054322-qd1k5r38as0tn1guepcaeit4rac3h86r.apps.googleusercontent.com',
    iosClientId: '1006258054322-73i32mbg0s087dj0gcvsdeeg7qbmaa9j.apps.googleusercontent.com',
    iosBundleId: 'com.marketlens.marketlens360mobile.dev',
  );

}